version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '01:00'
    open-pull-requests-limit: 10
    reviewers:
      - sonallux
    groups:
      angular-dependencies:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
      type-definitions:
        patterns:
          - "@types/*"
      formatting:
        patterns:
          - "prettier*"
          - "lint-staged"
          - "husky"
    ignore:
      - dependency-name: "@angular/*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular-devkit/*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@types/node"
        versions:
          - '>=20.0.0'
      - dependency-name: "jasmine-core"
        versions:
          - '>=5.0.0'
      - dependency-name: "@types/jasmine"
        versions:
          - '>=5.0.0'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '02:00'
    reviewers:
      - sonallux
