version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '01:00'
    open-pull-requests-limit: 10
    reviewers:
      - sonallux
    groups:
      angular-dependencies:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
    ignore:
      - dependency-name: "@angular/*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "@angular-devkit/*"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '02:00'
    reviewers:
      - sonallux
