name: Upsert comment
description: Create or update comment

inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  repository:
    description: 'The full name of the repository in which to create or update a comment.'
    default: ${{ github.repository }}
  issue-number:
    description: 'The number of the issue or pull request in which to create a comment.'
  body:
    description: 'The comment body. Cannot be used in conjunction with `body-path`.'
  body-path:
    description: 'The path to a file containing the comment body. Cannot be used in conjunction with `body`.'
  body-includes:
    description: 'A string to search for in the body of comments.'
  comment-author:
    description: 'The GitHub user name of the comment author.'

outputs:
  comment-id:
    description: 'The id of the created comment'
    value: ${{ steps.create-update-comment.outputs.comment-id }}

runs:
  using: composite
  steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: find-comment
      with:
        token: ${{ inputs.token }}
        issue-number: ${{ inputs.issue-number }}
        comment-author: ${{ inputs.comment-author }}
        body-includes: ${{ inputs.body-includes }}

    - name: Create or update comment
      id: create-update-comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ inputs.token }}
        issue-number: ${{ inputs.issue-number }}
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        body: ${{ inputs.body }}
        body-path: ${{ inputs.body-path }}
        edit-mode: replace
