name: After deployment

on:
  check_run:
    types:
      - completed

jobs:
  after-deploy:
    # if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: echo ${{ github.event.check_run }}
