name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18', '20' ]
    name: Build on NodeJS ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --force
      - name: Test
        run: npm run test:ci
      - name: Build
        run: npm run build
