name: Deploy preview

on: pull_request

permissions:
  checks: write
  pull-requests: write

jobs:
  deploy-preview:
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    name: Deploy preview to firebase
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.details_url }}
    environment:
      name: features
      url: ${{ steps.deploy.outputs.details_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Deploy preview to firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_MUSIC_7F2BA }}'
          expires: 14d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

  user-flow:
    name: Run user flows
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Measure user flows
        # TODO: use push-based/user-flow-gh-action@v0.4.1 when my PR is merged
        uses: sonallux/user-flow-gh-action@fix/121-keep-measurements
        with:
          url: ${{ needs.deploy-preview.outputs.url }}
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      - name: Upload user flow measurements
        uses: actions/upload-artifact@v3
        with:
          path: measures/
