name: Deploy preview

on: pull_request

permissions:
  pull-requests: write

jobs:
  deploy-preview:
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    name: Deploy preview
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    environment:
      name: features
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_SPOTIFY_CLIENT_D93B7 }}'
      - name: Deploy preview
        id: deploy
        uses: ./.github/actions/deploy-preview
        with:
          channel-id: pr${{github.event.pull_request.number}}-${{github.event.pull_request.head.ref}}
          expires: 14d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

  comment:
    name: Comment on PR
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - name: Create or update comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: deployment-preview-url
          message: |
            Visit the preview of this PR:

            ${{ needs.deploy-preview.outputs.url }}
