name: Deploy

on:
  push:
    branches:
      - disabled # main

concurrency:
  group: deploy-${{ github.ref }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: main
      url: https://angular-music-7f2ba.web.app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_MUSIC_7F2BA }}'
      - name: Deploy
        run: npx firebase deploy
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
