name: Deploy preview on PR

on: pull_request

permissions:
  checks: write
  pull-requests: write

jobs:
  deploy_preview:
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    name: Deploy preview on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_SPOTIFY_CLIENT_D93B7 }}'
      - name: Deploy preview
        id: deploy-preview
        uses: ./.github/actions/deploy-preview
        with:
          channelId: pr${{github.event.pull_request.number}}-${{github.event.pull_request.head.ref}}
          expires: 14d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
      - name: Deploy output
        run: echo "${{steps.deploy-preview.outputs.urls}}"
