name: Deploy preview

on: pull_request

permissions:
  checks: write
  pull-requests: write

jobs:
  deploy-preview:
    if: github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    name: Deploy preview
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.details_url }}
    environment:
      name: features
      url: ${{ steps.deploy.outputs.details_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Deploy preview
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_MUSIC_7F2BA }}'
          expires: 14d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
